### ISSUE TITLE
Improve This Footer 

### ISSUE THREAD

**Issue by waleedishfaq** [waleedcodes/React_Foodies_Website#1]
# Improve This Footer 
## link : https://react-foodies-website.vercel.app/
![Screenshot_12](https://github.com/waleedcodes/React_Foodies_Website/assets/153092192/cc3086bf-1e88-436a-928b-d0f1b1756756)

**Comment by waleedcodes** [comment]
## Fix #1 
![Screenshot_13](https://github.com/waleedcodes/React_Foodies_Website/assets/110061477/0f57cd04-fdd7-48db-8975-1dc46e3c8ae5)
